### ISSUE TITLE
Composer was unable to install the updates due to a dependency conflict

### ISSUE THREAD

**Issue by winterstetter** [manifestuk/smartdown.craft-plugin#14]
Composer output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package experience/smartdown 3.0.1 exists as experience/smartdown[3.0.0] but these are rejected by your constraint.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

---

Any hint, please?

**Comment by monooso** [comment]
@thomaswinterstetter Sorry, Thomas, I only just saw this.

That is a strange error. My only thought is that you may have attempted to install it before the Packagist and / or Craft indexes had updated properly. Version `3.0.1` [definitely exists](https://packagist.org/packages/experience/smartdown).

Can you try installing / updating it again?

**Comment by winterstetter** [comment]
@monooso  Stephen, thanks!

> … install it before the Packagist and / or Craft indexes had updated properly …

Maybe so. The plugin updated a couple of days after my post without further quarrel. Again, thank you for your help.

**Comment by monooso** [comment]
@thomaswinterstetter Good to hear you got it sorted. Thanks for letting me know.
